### ISSUE TITLE
UNABLE TO GO IN OUT

### ISSUE THREAD

**Issue by primoixi** [Lanzaned-Enterprises/LENT-Cyberbar#2]
EVERYTHING WORK FINE BUT UNABLE TO GO IN OR COME OUT FEELS LIKE INVISIBLE WALL AT DOOR

**Comment by thelynxtrain** [comment]
This is a mapping issue nothing that we would be able to provide support for. What I recommend is to see what MLOs you have nearby and disable them one by one to figure out which MLO has a collision there.

**Comment by primoixi** [comment]
ok sir, thanks for the information
